[versions]
agp = "8.13.2"
annotation = "1.9.1"
bc-jdk18on = "1.83"
kotlin = "2.3.0"
libcxx = "29.0.14206865"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
org-bouncycastle-bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bc-jdk18on" }
org-lsposed-libcxx-libcxx = { module = "org.lsposed.libcxx:libcxx", version.ref = "libcxx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

